#!/usr/bin/php

<?php

$root = "/var/www/html/ag";
$script_type = getenv('script_type');
$common_name = getenv('common_name');
$ifconfig_pool_remote_ip = getenv('ifconfig_pool_remote_ip');
$untrusted_ip = getenv('untrusted_ip');

#$cmd = exec("php $root/artisan user:auth $login $pwd", $o, $v);

# $data = json_encode($o[0]).PHP_EOL;
# $data = $result.PHP_EOL;

if ($script_type == 'client-connect') {
        $data = $common_name.'-connect-'.$ifconfig_pool_remote_ip.'-'.$untrusted_ip.PHP_EOL;
} elseif ($script_type == 'client-disconnect') {
        $data = $common_name.'-disconnect'.PHP_EOL;
}
$fp = fopen('/var/log/somefile.txt', 'a');
fwrite($fp, $data);
